### ISSUE TITLE
Documentation - Recommendations on how to discover devices

### ISSUE THREAD

**Issue by timpur** [homieiot/convention#93] opened 2018-05-02 03:38 UTC
As per title, I was thinking maybe we could alos recommend which topics and a order the order of those topics to discuss to discover a device, node and props ... Also some theory code on how to achieve discovery. This could help implentation of platforms trying to discover homie devices.

Alos maybe to same for clients devices wanting to be discovered, the best way to achieve implement. Order of messages ect 

Keep in mind it's just related to mqtt discovery ect....

**Comment by ingoogni** [comment] 2018-05-02 06:14
I would be interested in what every one expects auto discovery to be, as for me that is not clear at all.
Two non related devices for example, lets have a temperature sensor and lets have a PID controller, what is there to discover and what can be done with that.

**Comment by ThomDietrich** [comment] 2018-05-02 09:03
Duplicate of #51

**Comment by timpur** [comment] 2018-05-02 10:16
@ThomDietrich sorry, missed that some how.

**Closed** 2018-05-02 10:16 UTC

**Comment by davidgraeff** [comment] 2018-05-02 12:30
Copied from the readme:

> The Homie convention strives to be a communication definition on top of MQTT between IoT devices and controlling entities.

> MQTT supports easy and unrestricted message-based communication. However, MQTT doesn't define the structure and content of these messages and their relation. An IoT device publishes data and provides interaction possibilities but a controlling entity will need to be specifically configured to be able to interface with the device.

> The Homie convention **defines a standardized way of how IoT devices and services announce themselves** and their data on the communication channel. The Homie convention is thereby a crucial aspect in the support of automatic discovery, configuration and usage of devices and services over the MQTT protocol.

It is absolutely not about the semantic of an input or output. It is just about controllers knowing of all available inputs and ouputs and their data types (int, bool, string, etc).
