### ISSUE TITLE
Inconsistency in how ranges are specified

### ISSUE THREAD

**Issue by GideonLeGrange** [homieiot/convention#151] opened 2018-12-29 07:26 UTC
There is an inconsistency in how a range of values is defined between `$array` and `$format`. In once instance a range is specified using `-` as separator and in the other using `:`. 

From 6.3.1 Node Attributes: 

$array | Device → Controller | Range separated by a -. e.g. 0-2 for an array with the indexes 0, 1 and 2 | Yes |
-- | -- | -- | --

From 6.4.1 Property Attributes: 

$format | Device → Controller | Describes what are valid values for this property. | from:toDescribes a range of values e.g. 10:15.| Yes | 
-- | -- | -- | -- | --

**Comment by timpur** [comment] 2018-12-29 10:27
I think this is a good point and there is a ticket out there discussing how to reimplement node arrays, so hopefully this will be addressed in that ticket.

**Comment by davidgraeff** [comment] 2018-12-29 13:05
Thanks for the report.

Node arrays as such will not reappear (there is no advantage in having them), but different other ideas are discussed for "grouping" nodes and switching multiple nodes with one publish.

So I'm closing this issue. @GideonLeGrange I have written the openHAB controller and have not implemented node arrays. The website online verificator can't handle node arrays. Feel free to ignore arrays as well (they are broken by design).

**Closed as completed by davidgraeff** 2018-12-29 13:05 UTC
